// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Claim struct {
	ID             int32
	PolicyholderID int32
	Reason         sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Company struct {
	ID        int32
	Name      string
	Email     sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Credit struct {
	ID             int32
	SubscriptionID int32
	Amount         sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Package struct {
	ID        int32
	Name      string
	CompanyID int32
	Price     sql.NullString
	Terms     sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Policyholder struct {
	ID        int32
	Name      string
	Telnumber string
	Code      int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Service struct {
	ID          int32
	CompanyID   int32
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Subscription struct {
	ID             int32
	PolicyholderID int32
	PackageID      int32
	Credit         sql.NullString
	ExpiresOn      sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}
